"""
alerts.py
---------
Lightweight alerting stub that fires when a conjunction analysis returns
a HIGH risk classification. Supports two channels:

  - Telegram (via Bot API, using `requests` -- no extra dependency)
  - Email (via smtplib, Python standard library)

Both channels are OFF by default and degrade gracefully: if credentials
are not configured, the alert is simply logged/printed instead of sent,
so the demo never crashes or hangs waiting on real infrastructure.

Configure via environment variables (recommended) or Streamlit secrets
(`.streamlit/secrets.toml`):

    TELEGRAM_BOT_TOKEN = "123456:ABC-your-bot-token"
    TELEGRAM_CHAT_ID   = "987654321"

    ALERT_EMAIL_FROM   = "your-alert-bot@gmail.com"
    ALERT_EMAIL_TO     = "you@example.com"
    ALERT_EMAIL_PASSWORD = "app-specific-password"
    ALERT_SMTP_HOST    = "smtp.gmail.com"
    ALERT_SMTP_PORT    = "587"

Author: BSERC Internship Project
"""

import os
import smtplib
import ssl
from email.mime.text import MIMEText
from dataclasses import dataclass
from typing import Optional

import requests


def _get_config(key: str) -> Optional[str]:
    """Look up a config value from env vars first, then Streamlit secrets."""
    val = os.environ.get(key)
    if val:
        return val
    try:
        import streamlit as st
        return st.secrets.get(key)  # returns None if not present, no crash
    except Exception:
        return None


@dataclass
class AlertOutcome:
    channel: str
    sent: bool
    message: str


def format_alert_message(result) -> str:
    """Builds a human-readable alert message from a ConjunctionResult."""
    return (
        f"🚨 HIGH COLLISION RISK DETECTED 🚨\n"
        f"Primary: {result.object_a}\n"
        f"Threat object: {result.object_b}\n"
        f"Miss distance: {result.miss_distance_km:.3f} km\n"
        f"Relative speed: {result.relative_speed_kms:.2f} km/s\n"
        f"Closest approach (UTC): "
        f"{result.closest_approach_time.strftime('%Y-%m-%d %H:%M:%S')}\n"
        f"Pseudo-probability: {result.pseudo_probability*100:.3f}%\n"
        f"-- Generated by AI Space Debris Collision Prediction System --"
    )


def send_telegram_alert(message: str, timeout: int = 8) -> AlertOutcome:
    token = _get_config("TELEGRAM_BOT_TOKEN")
    chat_id = _get_config("TELEGRAM_CHAT_ID")

    if not token or not chat_id:
        return AlertOutcome(
            channel="telegram",
            sent=False,
            message="[DEMO MODE] Telegram not configured. Message would be:\n" + message,
        )

    try:
        url = f"https://api.telegram.org/bot{token}/sendMessage"
        resp = requests.post(url, json={"chat_id": chat_id, "text": message}, timeout=timeout)
        resp.raise_for_status()
        return AlertOutcome(channel="telegram", sent=True, message="Telegram alert sent.")
    except Exception as e:
        return AlertOutcome(channel="telegram", sent=False, message=f"Telegram send failed: {e}")


def send_email_alert(message: str, subject: str = "🚨 Satellite Collision Risk Alert") -> AlertOutcome:
    sender = _get_config("ALERT_EMAIL_FROM")
    recipient = _get_config("ALERT_EMAIL_TO")
    password = _get_config("ALERT_EMAIL_PASSWORD")
    smtp_host = _get_config("ALERT_SMTP_HOST") or "smtp.gmail.com"
    smtp_port = int(_get_config("ALERT_SMTP_PORT") or 587)

    if not sender or not recipient or not password:
        return AlertOutcome(
            channel="email",
            sent=False,
            message="[DEMO MODE] Email not configured. Message would be:\n" + message,
        )

    try:
        msg = MIMEText(message)
        msg["Subject"] = subject
        msg["From"] = sender
        msg["To"] = recipient

        context = ssl.create_default_context()
        with smtplib.SMTP(smtp_host, smtp_port, timeout=10) as server:
            server.starttls(context=context)
            server.login(sender, password)
            server.sendmail(sender, [recipient], msg.as_string())
        return AlertOutcome(channel="email", sent=True, message="Email alert sent.")
    except Exception as e:
        return AlertOutcome(channel="email", sent=False, message=f"Email send failed: {e}")


def notify_high_risk(result) -> list:
    """
    Fires both alert channels for a HIGH-risk ConjunctionResult and
    returns a list of AlertOutcome so the caller (UI) can display what
    happened on each channel.
    """
    message = format_alert_message(result)
    outcomes = [
        send_telegram_alert(message),
        send_email_alert(message),
    ]
    return outcomes
